apiVersion: v1
kind: Service
metadata:
  name: gopher-svc
  namespace: gopher-ns
spec:
  selector:
    app: gopher-app
  ports:
    - name: debug-port
      port: 3000
      targetPort: debug-port
      nodePort: 30300
    - name: api-port
      port: 4000
      targetPort: api-port
      nodePort: 30400
  type: NodePort
